# Generated by Django 6.1 on 2026-08-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_code',
            field=models.CharField(blank=True, help_text='Auto-generated on save if left blank (e.g. CU-0001 / SP-0001).', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(blank=True, default='Bangladesh', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contact',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
