# Generated by Django 6.1 on 2026-08-20 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_contact_city_contact_contact_code_contact_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='advance_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='contact',
            name='custom_field_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='custom_field_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='pay_term_days',
            field=models.PositiveIntegerField(blank=True, help_text='Payment due within this many days of invoice/purchase. Blank = no term.', null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact_code',
            field=models.CharField(blank=True, help_text='Auto-generated on save if left blank (e.g. CO0001).', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='customer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='pos.customergroup'),
        ),
    ]
