# Generated by Django 6.1 on 2026-08-20 13:17
#
# NOTE: hand-adjusted from the autogenerated version. A direct
# AlterField from the old CharField 'unit' straight to a ForeignKey
# is not a safe type change on Postgres (varchar -> bigint isn't
# auto-castable) -- it would fail against a real database with any
# existing POSProduct rows. Dropping the old column and adding the
# new nullable FK avoids that entirely; the only cost is that any
# pre-existing free-text unit value (e.g. the default "Pc(s)") isn't
# preserved, which is acceptable this early -- there's no real
# product catalog yet, and every product just needs its unit reset
# via the new Units page afterward.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_customergroup_contact_advance_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('short_name', models.CharField(max_length=20)),
                ('allow_decimal', models.BooleanField(default=False, help_text='Can quantities of this unit be fractional (e.g. 1.5 kg)?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='posproduct',
            name='unit',
        ),
        migrations.AddField(
            model_name='posproduct',
            name='unit',
            field=models.ForeignKey(
                blank=True,
                help_text='Every product should have a unit; nullable only for skeleton/legacy rows.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='products',
                to='pos.unit',
            ),
        ),
    ]
