# Generated by Django 6.1 on 2026-08-20 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_unit_alter_posproduct_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Percentage, e.g. 15.00 for 15%.', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='posproduct',
            name='custom_field_1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='custom_field_2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='custom_field_3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='custom_field_4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pos/products/'),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='not_for_selling',
            field=models.BooleanField(default=False, help_text='Raw material / internal-use item -- excluded from the Sell screen.'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('opening_stock', 'Opening Stock'), ('purchase', 'Purchase'), ('sale', 'Sale'), ('purchase_return', 'Purchase Return'), ('sale_return', 'Sale Return'), ('adjustment_increase', 'Adjustment (Increase)'), ('adjustment_decrease', 'Adjustment (Decrease)'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out')], max_length=25),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.brand'),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.category'),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='pos.taxrate'),
        ),
    ]
