# Generated by Django 6.1 on 2026-08-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0005_brand_category_taxrate_posproduct_custom_field_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='barcode_type',
            field=models.CharField(choices=[('c128', 'Code 128 (C128)'), ('c39', 'Code 39 (C39)'), ('ean13', 'EAN-13'), ('ean8', 'EAN-8'), ('upca', 'UPC-A'), ('upce', 'UPC-E')], default='c128', max_length=10),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='brochure',
            field=models.FileField(blank=True, null=True, upload_to='pos/products/brochures/'),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='enable_serial_tracking',
            field=models.BooleanField(default=False, help_text='Capture a description/IMEI/serial number per unit sold (used by Sell later).'),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='locations',
            field=models.ManyToManyField(blank=True, help_text='Which branches sell this product -- not a stock quantity.', related_name='available_products', to='pos.location'),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='manage_stock',
            field=models.BooleanField(default=True, help_text="Off for services/items that don't need stock tracking at all."),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
