# Generated by Django 6.1 on 2026-08-21 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_purchasereturnitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='additional_expenses_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='additional_expenses_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='attached_document',
            field=models.FileField(blank=True, null=True, upload_to='pos/sales/documents/'),
        ),
        migrations.AddField(
            model_name='sale',
            name='delivered_to',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Raw input: a percentage (0-100) if discount_type=percentage, else a flat amount.', max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('percentage', 'Percentage'), ('fixed', 'Fixed')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='pay_term_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_details',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sale',
            name='shipping_documents',
            field=models.FileField(blank=True, null=True, upload_to='pos/sales/shipping/'),
        ),
        migrations.AddField(
            model_name='sale',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='pos.taxrate'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='payment_status',
            field=models.CharField(choices=[('due', 'Due'), ('partial', 'Partial'), ('paid', 'Paid')], default='due', max_length=10),
        ),
        migrations.AddField(
            model_name='salereturn',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='return_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='SaleReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.salereturn')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.posvariant')),
            ],
        ),
    ]
