# Generated by Django 6.1 on 2026-08-27 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_stockadjustment_stockadjustmentitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='attached_document',
            field=models.FileField(blank=True, null=True, upload_to='pos/expenses/documents/'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_for_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_expenses_for_contact', to='pos.contact'),
        ),
        migrations.AddField(
            model_name='expense',
            name='expense_for_user',
            field=models.ForeignKey(blank=True, help_text='"Expense for" -- e.g. a salary payment tagged to a staff member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_expenses_for_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_refund',
            field=models.BooleanField(default=False, help_text='Marks this as money coming back rather than going out -- nets against total expense in reports rather than adding to it.'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_status',
            field=models.CharField(choices=[('due', 'Due'), ('partial', 'Partial'), ('paid', 'Paid')], default='due', max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_interval_unit',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('months', 'Months'), ('years', 'Years')], max_length=10),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_interval_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='recurring_repetitions',
            field=models.PositiveIntegerField(blank=True, help_text='Blank = repeats indefinitely.', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='reference_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Must be a subcategory of `category`, if set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_expenses', to='pos.expensecategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='tax_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='pos.taxrate'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='category_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pos.expensecategory'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateTimeField(),
        ),
    ]
