# Generated by Django 6.1 on 2026-08-27 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_expense_attached_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_note', models.TextField(blank=True)),
                ('attached_document', models.FileField(blank=True, null=True, upload_to='pos/purchase_payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_purchase_payments_created', to=settings.AUTH_USER_MODEL)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.purchase')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(blank=True, max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_on', models.DateTimeField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_note', models.TextField(blank=True)),
                ('attached_document', models.FileField(blank=True, null=True, upload_to='pos/sale_payments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sale_payments_created', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.sale')),
            ],
            options={
                'ordering': ['-paid_on', '-id'],
            },
        ),
    ]
