# Generated by Django 6.1 on 2026-08-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_alter_expense_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='pos.category'),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='subcategory',
            field=models.ForeignKey(blank=True, help_text='Must be a subcategory of `category`, if set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_products', to='pos.category'),
        ),
    ]
