# Generated by Django 6.1 on 2026-08-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_category_parent_posproduct_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentPrefix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('purchase', 'Purchase'), ('purchase_return', 'Purchase Return'), ('sale_final', 'Sale (Final)'), ('sale_draft', 'Sale Draft'), ('sale_quotation', 'Quotation'), ('sale_suspended', 'Suspended Sale'), ('sale_return', 'Sell Return'), ('stock_adjustment', 'Stock Adjustment'), ('expense', 'Expense'), ('purchase_payment', 'Purchase Payment'), ('sale_payment', 'Sale Payment'), ('contact', 'Contact Code'), ('product_sku', 'Product SKU')], max_length=20, unique=True)),
                ('prefix', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='currency_symbol_placement',
            field=models.CharField(choices=[('before', 'Before amount'), ('after', 'After amount')], default='before', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='date_format',
            field=models.CharField(choices=[('dd-mm-yyyy', 'dd-mm-yyyy'), ('mm/dd/yyyy', 'mm/dd/yyyy'), ('yyyy-mm-dd', 'yyyy-mm-dd')], default='dd-mm-yyyy', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='default_profit_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='business',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='stock_accounting_method',
            field=models.CharField(choices=[('fifo', 'FIFO (First In First Out)'), ('lifo', 'LIFO (Last In First Out)'), ('average', 'Weighted Average')], default='fifo', max_length=10),
        ),
        migrations.AddField(
            model_name='business',
            name='time_format',
            field=models.CharField(choices=[('12h', '12 Hour'), ('24h', '24 Hour')], default='12h', max_length=3),
        ),
        migrations.AddField(
            model_name='business',
            name='transaction_edit_days',
            field=models.PositiveIntegerField(default=30, help_text='Not yet enforced -- stored for when transaction editing is built.'),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='landmark',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='location_id',
            field=models.CharField(blank=True, help_text='Optional external/legacy code for this branch.', max_length=50),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='location',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
