# Generated by Django 6.1 on 2026-08-28 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_documentprefix_business_currency_symbol_placement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='pos.location'),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_levels', to='pos.location'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='pos.location'),
        ),
    ]
