# Generated by Django 6.1 on 2026-08-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_alter_batch_location_alter_stocklevel_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='receipt_footer_text',
            field=models.CharField(blank=True, help_text="e.g. 'Thank you for shopping with us!'", max_length=255),
        ),
        migrations.AddField(
            model_name='business',
            name='receipt_paper_width',
            field=models.CharField(choices=[('58mm', 'Thermal 58mm'), ('80mm', 'Thermal 80mm'), ('a4', 'A4 / Letter')], default='80mm', help_text='Drives the print CSS width for customer/seller receipts.', max_length=5),
        ),
        migrations.AddField(
            model_name='business',
            name='receipt_show_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='posvariant',
            name='barcode',
            field=models.CharField(blank=True, help_text='Auto-generated in-store EAN-13 (GS1 prefix 20). Scannable by any retail scanner.', max_length=13, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='posvariant',
            name='color',
            field=models.CharField(blank=True, help_text='Optional structured colour; not yet used for display.', max_length=50),
        ),
        migrations.AddField(
            model_name='posvariant',
            name='size',
            field=models.CharField(blank=True, help_text='Optional structured size; not yet used for display.', max_length=50),
        ),
    ]
