# Generated by Django 6.1.1 on 2026-09-05 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_backfill_variant_barcodes'),
        ('products', '0010_alter_category_id_alter_color_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='POSProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pos/products/gallery/')),
                ('image_type', models.CharField(choices=[('cover', 'Cover'), ('hover', 'Hover'), ('gallery', 'Gallery')], default='gallery', max_length=20)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AlterModelOptions(
            name='posvariant',
            options={'ordering': ['product', 'color', 'size']},
        ),
        migrations.AddField(
            model_name='location',
            name='is_online_channel',
            field=models.BooleanField(default=False, help_text='The single location whose stock the online storefront reads from and sells against. Only one per business.'),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='fabric_and_care',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='fitting',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='is_new_arrival',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='is_on_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='online_discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="If set, shown/charged online instead of the variant's selling_price.", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='publish_online',
            field=models.BooleanField(default=True, help_text='If on, this product (and its variants) is created/kept in sync on the storefront.'),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='shipping_and_return',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='short_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='storefront_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_products', to='products.category'),
        ),
        migrations.AddField(
            model_name='posproduct',
            name='storefront_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_products', to='products.producttype'),
        ),
        # color/size were free-text CharFields; existing rows may hold
        # "" which Postgres can't cast to bigint for a plain AlterField
        # (ALTER COLUMN TYPE). Drop and recreate instead -- any old
        # free-text values are lost, but nothing here was ever a
        # storefront-facing product, so that's fine.
        migrations.RemoveField(
            model_name='posvariant',
            name='color',
        ),
        migrations.RemoveField(
            model_name='posvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='posvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_variants', to='products.color'),
        ),
        migrations.AddField(
            model_name='posvariant',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_variants', to='products.size'),
        ),
        migrations.AlterField(
            model_name='posvariant',
            name='variant_name',
            field=models.CharField(blank=True, help_text='Optional free-text override label -- for non-fashion/no-variant items only.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_online_channel', True)), fields=('business',), name='one_online_channel_per_business'),
        ),
        migrations.AddConstraint(
            model_name='posvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_pos_variant_color_size'),
        ),
        migrations.AddField(
            model_name='posproductfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pos.posproduct'),
        ),
        migrations.AddField(
            model_name='posproductimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pos.posproduct'),
        ),
    ]
