# Generated by Django 6.1.1 on 2026-09-08 08:29

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Sum


def merge_stock_levels_per_variant(apps, schema_editor):
    """
    Collapse every variant's per-location StockLevel rows into one,
    summing their quantities, before the unique-per-variant constraint
    is added below. This is what makes "1000 at Branch A + 24 at
    Branch B" become a single shared "1024" row per variant, per the
    move to one shared stock pool across every location and the
    online storefront.
    """
    StockLevel = apps.get_model("pos", "StockLevel")
    db_alias = schema_editor.connection.alias

    sums = (
        StockLevel.objects.using(db_alias)
        .values("variant_id")
        .annotate(total_qty=Sum("quantity"))
    )

    for row in sums:
        variant_id = row["variant_id"]
        total_qty = row["total_qty"] or 0
        rows = list(
            StockLevel.objects.using(db_alias)
            .filter(variant_id=variant_id)
            .order_by("id")
        )
        keeper = rows[0]
        keeper.quantity = total_qty
        keeper.save(update_fields=["quantity"])
        for extra in rows[1:]:
            extra.delete()

    # Immediately resync every published product's storefront mirror
    # to the newly-merged number -- otherwise a product with no new
    # movement after this migration would keep showing its old,
    # single-location-only stock until its next sale/purchase.
    ProductVariant = apps.get_model("products", "ProductVariant")
    for pv in ProductVariant.objects.using(db_alias).exclude(pos_source__isnull=True):
        stock_level = (
            StockLevel.objects.using(db_alias).filter(variant_id=pv.pos_source_id).first()
        )
        new_stock = int(stock_level.quantity) if stock_level else 0
        if pv.stock != new_stock:
            pv.stock = new_stock
            pv.save(update_fields=["stock"])


def noop_reverse(apps, schema_editor):
    # Not reversible -- the per-location split isn't recoverable once
    # merged, since we no longer know which location each unit came from.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_posproductfeature_posproductimage_and_more'),
    ]

    operations = [
        migrations.RunPython(merge_stock_levels_per_variant, noop_reverse),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='stocklevel',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='pos.posvariant', unique=True),
        ),
        migrations.RemoveField(
            model_name='stocklevel',
            name='location',
        ),
    ]
