# Generated by Django 6.1.1 on 2026-09-05 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_posproductfeature_posproductimage_and_more'),
        ('products', '0010_alter_category_id_alter_color_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pos_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_product', to='pos.posproduct'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='pos_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storefront_variant', to='pos.posvariant'),
        ),
    ]
